//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Domain.Resources; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class ErrorMessages {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ErrorMessages() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthService.Domain.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to E-mail already exists.
    /// </summary>
    public static string EmailAlreadyExists {
        get {
            return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to This account has been banned.
    /// </summary>
    public static string ThisAccountHasBeenBanned {
        get {
            return ResourceManager.GetString("ThisAccountHasBeenBanned", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Token has expired.
    /// </summary>
    public static string TokenHasExpired {
        get {
            return ResourceManager.GetString("TokenHasExpired", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Token value is invalid.
    /// </summary>
    public static string TokenValueIsInvalid {
        get {
            return ResourceManager.GetString("TokenValueIsInvalid", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Username already exists.
    /// </summary>
    public static string UsernameAlreadyExists {
        get {
            return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to User not found.
    /// </summary>
    public static string UserNotFound {
        get {
            return ResourceManager.GetString("UserNotFound", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to You have already used this password.
    /// </summary>
    public static string YouHaveAlreadyUsedThisPassword {
        get {
            return ResourceManager.GetString("YouHaveAlreadyUsedThisPassword", resourceCulture);
        }
    }
}
