//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthService.Domain.Resources.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ban has been removed.
        /// </summary>
        public static string AccountBanHasBeenRemoved {
            get {
                return ResourceManager.GetString("AccountBanHasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been banned.
        /// </summary>
        public static string AccountHasBeenBanned {
            get {
                return ResourceManager.GetString("AccountHasBeenBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail has been changed.
        /// </summary>
        public static string EmailHasBeenChanged {
            get {
                return ResourceManager.GetString("EmailHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed.
        /// </summary>
        public static string PasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("PasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reseted.
        /// </summary>
        public static string PasswordHasBeenReseted {
            get {
                return ResourceManager.GetString("PasswordHasBeenReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token to reset password has been sent to your e-mail.
        /// </summary>
        public static string TokenToResetPasswordHasBeenSentToYourEmail {
            get {
                return ResourceManager.GetString("TokenToResetPasswordHasBeenSentToYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username has been changed.
        /// </summary>
        public static string UsernameHasBeenChanged {
            get {
                return ResourceManager.GetString("UsernameHasBeenChanged", resourceCulture);
            }
        }
    }
}
